version: "3.8"
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80" # Mapeia a porta 8888 do host para a porta 80 do contêiner
    volumes:
      - ./app:/var/www/html # Permite editar os arquivos localmente e refletir no contêiner
    restart: always